server:
  port: 8070
spring:
  application:
    name: demo
  thread-pool:
    max-thread-count: 6
  datasource:
    password: postgres
    url: jdbc:postgresql://postgres:5432/reportsdb
    username: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  #    queue: commandQueueProject
  profiles:
    active: default